### PR TITLE
First production run

### PR DESCRIPTION
**Pull request by Joshdpaul**
This PR is the first draft of a production-ready routine to fetch and format data for the EPA-Justice-HIA project.

The majority of this code is parsing entries in the `NCRPlaces_Census_{MMDDYYYY}.csv` table into requests to the various APIs. There is a quite a bit of string chopping and table wrangling to accomplish the fetching and merging of all this data into a single output. I realize that this kind of code can be difficult to review without seeing interim outputs, so to expose some of those interim pieces, I called a few of the individual data fetching functions in `fetch_data_and_export.ipynb` and included some URL request printing to allow you to see the API requests, the JSON returned, and compare them with the reformatted function outputs. 

**TO TEST:**

- Read the `README.md`
- Run `fetch_data_and_export.ipynb`, paying particular attention to the testing cells in the first part of the notebook. Investigate some of the URLs, and make sure the values you see in the printed dataframes match those returned by the API.
- Review the code for the `run_fetch_and_merge()` function to see how it orchestrates the individual data fetching steps.  This function uses multiprocessing and produces a single table output (`data_to_export.csv`). 
- Review `data_to_export.csv`. The result should be identical to the version committed in this repo. Is this a reasonable table format for incorporating into NCR?
- Check out the functions in `functions.py`. Unless something breaks, there is no need for an in-depth review here ... but see if you can follow the processing logic backwards from `run_fetch_and_merge()`

### CODE REVIEW

**Review by cstephen — CHANGES_REQUESTED** [review]
I kicked the tires on this PR a bit, and things look great overall!

I spot-checked the console output and corresponding code that maps a place's GVV identifier to a `GEOIDFQ`, and then uses different substrings of the `GEOIDFQ` to fetch CDC and Census data. I also see how the IDs (dict keys) set in `var_dict` from `luts.py` correspond to the API outputs and table columns in `data_to_export.csv`. I've also spot-checked that the data coming from the various CDC and Census API responses ends up in the right columns in `data_to_export.csv`, and that the numbers match.

There's a lot of work happening here, and it's going to make our lives much easier and NCR much snappier having all of the data compiled ahead of time. `data_to_export.csv` looks like everything we'll need to start incorporating the data into NCR, even if the final format of the data is still to be decided (CSV vs. shapefile, or whatever).

I did run into a small snag getting my conda environment set up. I decided to run `fetch_data_and_export.ipynb` locally on my MacBook since it doesn't have any external dependencies (like CMIP6 data on Chinook or similar), but I ran into difficulties getting it to find all of the needed Python packages from the available conda channels.

I finally got it to work by removing each package's "build identifier" from `environment.yml` (i.e., the second "=" sign and everything after it). @Joshdpaul, I think if you export your conda environment using this command it will fix this in a cleaner way than my hack job, and make `environment.yml` more portable across operating systems:

```
conda env export --no-builds > environment.yml
```

- [ ] Please give the command above a try and `git push` the modified `environment.yml` and I'll verify that this fixes the problem on my end.

- [ ] Also, please see the screenshot of `data_to_export.csv` below. I'm 97% sure that the highlighted cells erroneously copied/inherited the comment from the Eagle River rows above them. If so, there may be other rows that were impacted by the same bug.
image

**Comment by Joshdpaul** [comment]
Thanks for the detailed review here, Craig. 

Good catch on the duplicated comments! I fixed that bug via [1ebd680](https://github.com/ua-snap/epa-justice/pull/3/commits/1ebd68095517a59d47da1a60ece1b12a65d6b915) and [a93ec66](https://github.com/ua-snap/epa-justice/pull/3/commits/a93ec664a554050a763f36971068db808238094a). The rows affected were places having simple one-to-one relationships with tract geography. These were missed by the conditional statements and so inherited the comment from the previous iteration (previous row). Should be good to go now.

I also re-exported the `environment.yml` as per your suggestion - please give that a shot and see what happens.

**Review by cstephen — APPROVED** [review]
Thanks, Josh! The fix to the comment column generation looks good.

I also tried the new `environment.yml` file, and unfortunately it wasn't the easy fix I was hoping it would be. I had forgotten I did some manual version adjustments in my original modification of the `environment.yml` file to make it work on my MacBook. It's looking like only foolproof & future proof way to make this work across all systems would be to remove the versions from `environment.yml` entirely and let conda decide what versions to use, which is fraught with peril and probably not what we want to do. So, forget I said anything! Maybe just add a note to the README saying what system to run the notebook on.

Anyway, this gets my approval!

**Review by BobTorgerson — APPROVED** [review]
The notebook created a new version of the CSV for me and the structure of the CSV looks good to me! It should be easy to integrate into NCR and / or the API for this project.

**Pull request merged**
